global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "go-streaming-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:3003"]
